<a href="https://colab.research.google.com/github/Hafiz-wave/Project-for-Data-Science-Analyst/blob/main/Diabetes_Prediction_Using_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/diabetes.csv')

df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
X = df.iloc[:, :-1].values
X[:8]

array([[6.000e+00, 1.480e+02, 7.200e+01, 3.500e+01, 0.000e+00, 3.360e+01,
        6.270e-01, 5.000e+01],
       [1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01],
       [5.000e+00, 1.160e+02, 7.400e+01, 0.000e+00, 0.000e+00, 2.560e+01,
        2.010e-01, 3.000e+01],
       [3.000e+00, 7.800e+01, 5.000e+01, 3.200e+01, 8.800e+01, 3.100e+01,
        2.480e-01, 2.600e+01],
       [1.000e+01, 1.150e+02, 0.000e+00, 0.000e+00, 0.000e+00, 3.530e+01,
        1.340e-01, 2.900e+01]])

In [ ]:
y = df['Outcome'].values
y[:8]

array([1, 0, 1, 0, 1, 0, 1, 0])

In [ ]:

from sklearn.preprocessing import LabelEncoder

label_Pregnancies = LabelEncoder()

X[:,0] = label_Pregnancies.fit_transform(X[:,0])

label_Glucose = LabelEncoder()

X[:,1] = label_Glucose.fit_transform(X[:,1])

label_BloodPressure = LabelEncoder()

X[:,2] = label_BloodPressure.fit_transform(X[:,2])

label_SkinThickness = LabelEncoder()

X[:,3] = label_SkinThickness.fit_transform(X[:,3])

label_Insulin = LabelEncoder()

X[:,4] = label_Insulin.fit_transform(X[:,4])

label_BMI = LabelEncoder()

X[:,5] = label_BMI.fit_transform(X[:,5])

label_DiabetesPedigreeFunction = LabelEncoder()

X[:,6] = label_DiabetesPedigreeFunction.fit_transform(X[:,6])

label_Age = LabelEncoder()

X[:,7] = label_Age.fit_transform(X[:,7])

X[:8]

array([[  6.,  86.,  22.,  28.,   0., 123., 350.,  29.],
       [  1.,  23.,  19.,  22.,   0.,  62., 196.,  10.],
       [  8., 121.,  17.,   0.,   0.,  30., 368.,  11.],
       [  1.,  27.,  19.,  16.,  62.,  77.,  53.,   0.],
       [  0.,  75.,   4.,  28., 102., 209., 514.,  12.],
       [  5.,  54.,  23.,   0.,   0.,  53.,  80.,   9.],
       [  3.,  16.,   8.,  25.,  57., 103., 118.,   5.],
       [ 10.,  53.,   0.,   0.,   0., 140.,  23.,   8.]])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

X_train.shape

(576, 8)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

X_train[ :8]

array([[ 0.06459212, -0.81446516, -0.79403397,  0.08636704, -0.78607049,
        -0.53820876,  0.19012306, -0.94468719],
       [ 0.36223259, -0.34686961,  0.09426623,  0.47260473, -0.78607049,
        -1.25161329,  0.02739207, -0.52057198],
       [-1.12596979,  1.95770844,  1.31567901,  0.31810966,  0.33640607,
         0.7187421 , -0.42542461,  0.15801237],
       [ 0.65987307, -0.61406707, -0.23884634, -1.14959358, -0.78607049,
        -1.18367001, -0.77211238, -0.35092589],
       [ 1.85043498,  0.02052689,  0.53841633,  0.70434735, -0.78607049,
        -0.64012369,  0.45898297,  1.00624281],
       [-0.53068884, -0.24667057, -0.12780882,  0.0091195 , -0.78607049,
        -0.45327964, -1.57869209, -0.69021806],
       [ 0.36223259, -0.41366898, -0.57195892,  1.47682274,  0.77398167,
         0.59984134,  0.46605823, -0.69021806],
       [-0.82832931,  1.72391067,  0.20530376, -1.14959358, -0.78607049,
         0.76969956, -1.59284262,  0.4124815 ]])

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import jaccard_score

DS = DecisionTreeClassifier()
#training
DS.fit(X_train, y_train)

#prediction

y_hat = DS.predict(X_test)

#evaluation

print('The accuracy is :', accuracy_score(y_test, y_hat))
print('The confusion matrix is :', confusion_matrix(y_test, y_hat))

#accuracy

accuracy_score(y_test, y_hat)

The accuracy is : 0.6927083333333334
The confusion matrix is : [[102  21]
 [ 38  31]]


0.6927083333333334

In [ ]:
print('The jaccard score is :', jaccard_score(y_test, y_hat, average='micro'))

The jaccard score is : 0.5298804780876494


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#MODELLING
SVM_bank = SVC()

#TRAINING

SVM_bank.fit(X_train, y_train)

#TESTING

y_hat = SVM_bank.predict(X_test)

#EVALUATION
print('The accuracy based on RBF kernel is :', (accuracy_score( y_test, y_hat))*100)

The accuracy based on RBF kernel is : 78.64583333333334


In [ ]:
#TRAINING
SVM_bank = SVC(kernel = 'linear')
SVM_bank.fit(X_train, y_train)

#TESTING

y_hat = SVM_bank.predict(X_test)

#EVALUATION
print('The accuracy based on linear kernel is :', (accuracy_score( y_test, y_hat))*100)

The accuracy based on linear kernel is : 78.64583333333334


In [ ]:
#TRAINING
SVM_bank = SVC(kernel = 'poly')
SVM_bank.fit(X_train, y_train)

#TESTING

y_hat = SVM_bank.predict(X_test)

#EVALUATION
print('The accuracy based on polynomial kernel is :', (accuracy_score( y_test, y_hat))*100)

The accuracy based on polynomial kernel is : 76.5625


In [ ]:
#TRAINING
SVM_bank = SVC(kernel = 'sigmoid')
SVM_bank.fit(X_train, y_train)

#TESTING

y_hat = SVM_bank.predict(X_test)

#EVALUATION
print('The accuracy based on sigmoid kernel is :', (accuracy_score( y_test, y_hat))*100)

The accuracy based on sigmoid kernel is : 68.22916666666666
